version: "0.1"

services:
  arrowhead-database:
    extends:
      file: arrowhead-core/docker-compose.yaml
      service: arrowhead-database
    
  arrowhead-serviceregistry:
    container_name: arrowhead-serviceregistry
    image: aitiaiiot/arrowhead-system:4.6.1
    environment:
      SYSTEM_NAME: serviceregistry
    env_file:
      - ./arrowhead-core/.env
    volumes:
      - ./arrowhead-core/serviceregistry/application.properties:/opt/arrowhead/application.properties
      - ./arrowhead-core/serviceregistry/certificates:/opt/arrowhead/certificates
    ports:
      - 8443:8443
  
  arrowhead-authorization:
    container_name: arrowhead-authorization
    image: aitiaiiot/arrowhead-system:4.6.1
    environment:
      SYSTEM_NAME: authorization
    env_file:
      - ./arrowhead-core/.env
    volumes:
      - ./arrowhead-core/authorization/application.properties:/opt/arrowhead/application.properties
      - ./arrowhead-core/authorization/certificates:/opt/arrowhead/certificates
    ports:
      - 8445:8445
      
  arrowhead-orchestrator:
    container_name: arrowhead-orchestrator
    image: aitiaiiot/arrowhead-system:4.6.1
    environment:
      SYSTEM_NAME: orchestrator
    env_file:
      - ./arrowhead-core/.env
    volumes:
      - ./arrowhead-core/orchestrator/application.properties:/opt/arrowhead/application.properties
      - ./arrowhead-core/orchestrator/certificates:/opt/arrowhead/certificates
    ports:
      - 8441:8441

  work-handler:
    container_name: work-handler
    ports:
      - "8001:8001"
    build: 
      context: work-handler
      dockerfile: ../work-handler.Dockerfile

  mongodb:
    image: mongo:latest
    ports:
      - "30000:27017"
    volumes:
      - mongo-data:/data/db
  
volumes:
  arrowhead-database:
  mongo-data: